import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import CustomThemeProvider from "@/theme";
import { Bebas_Neue, Public_Sans } from "next/font/google";

const bebasNeue = Bebas_Neue({
 subsets: ["latin"],
 weight: "400",
 variable: "--display-font",
});

const publicSans = Public_Sans({
 subsets: ["latin"],
 variable: "--body-font",
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en" className={`${publicSans.variable} ${bebasNeue.variable}`}>
   <body>
    <AppRouterCacheProvider>
     <CustomThemeProvider>
      <div className="bg-[var(--foreground)] text-[var(--text)]">
       {children}
      </div>
     </CustomThemeProvider>
    </AppRouterCacheProvider>
   </body>
  </html>
 );
}
